### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage. 

### ISSUE THREAD

**Issue by expipiplus1** [csabahruska/bullet#3]
It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by csabahruska** [comment]
Thanks for the notification!
It is fixed now.

**Comment by expipiplus1** [comment]
Thanks!

**Comment by csabahruska** [comment]
Do you use this package?

**Comment by expipiplus1** [comment]
No, sorry! I was just browsing different physics engines for haskell.
